'use client'
import './globals.css'
import { Providers } from '@/chakra/Provider'
// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body>
        <Providers>
          {children}  
        </Providers>
      </body>
    </html>
  )
}
